name: Test Action

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 23f1000296@ds.study.iitm.ac.in
        run: echo "Hello, world! This is my GitHub Action."
